variables:
  NAME: homed-zigbee
  PACKAGE_EXTRA: mkdir -p deploy/data/opt/homed-zigbee
  DOCKER_EXTRA: cp -r deploy/data/usr/share/homed-zigbee deploy/docker/share

include:
- project: 'homed/services/homed-common'
  file: '.gitlab-ci/pipeline.yml'
